USE DB_CLIENTES;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_CLIENTES' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

-- USE DB_HUELLASPAGO;

-- SELECT
--     ROUTINE_SCHEMA,
--     ROUTINE_NAME,
--     'DB_HUELLASPAGO' AS DB
-- FROM
--     INFORMATION_SCHEMA.ROUTINES
-- WHERE
--     ROUTINE_TYPE = 'PROCEDURE'
-- ORDER BY
--     ROUTINE_NAME;

USE DB_LOGAPPSERVER;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_LOGAPPSERVER' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DBEFECTY;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DBEFECTY' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DEVSIEWEB;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DEVSIEWEB' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE WIKI;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'WIKI' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSANTIFRAUDE;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSANTIFRAUDE' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSBILLETERA;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSBILLETERA' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSBIOMETRIA;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSBIOMETRIA' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSBROKER;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSBROKER' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSSEGURIDAD;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSSEGURIDAD' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;

USE DB_MSTRANSACCION;

SELECT
    ROUTINE_SCHEMA,
    ROUTINE_NAME,
    'DB_MSTRANSACCION' AS DB
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE = 'PROCEDURE'
ORDER BY
    ROUTINE_NAME;
